// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puksbtgpxmqugsndfmrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1a3NidGdweG1xdWdzbmRmbXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODIyMDAsImV4cCI6MjA2NzQ1ODIwMH0.jpcYxM2paW0JQ5FbPiX0DQtkvzPgv_NELKUWBJ_i0tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});